package string;

import java.util.HashMap;
import java.util.Map;

//Leetcode #3
public class LongestSubstring {

	public static void main(String[] args) {

		LongestSubstring obj = new LongestSubstring();
        System.out.println(obj.longestSubstring("ODYxpsSaKuynFENgmdgAXJGibxMIDiCoEteYViBJUhSHMbJSYTlKeqiKuMzhhpFpnFvzWNwFpbsfKAWglCSsQHywjrIsQACGEQWHWRQLZkZExwzdXDgBvVYpoyPWNHqauJZOlKQkdWxMVqLJbKHyWhfttZFfNprWCigRwCuZQHhvnYaCHonmcOTjCiDcATlxLirmuKyknaXZyucAogIOtPUdzLMOrZeZpOUVKHOXPMMEnJLrQqyiukDfxNsqxAgSyhCecIRGpmCFdrwwcVwOohrHVxmfdiwgpFOkySkALEyaVEwRkNIBZusVnkbQdZEcqwuuYOelbvAVivaTTBbBqOfiRlVcamBZLZmmWybziBFZDlStXjXAMDyHEyFtuKLwpuSATNmpqdrSpCebrhuXGlUEXLpSLQufTHdTCbgyTQAPFNGfKbIAULmuIKUehTQVZHzYdkZWneuEvJLedHuIhoBZPNKIltkrOLqCGxGwiuDyYNvUSgqXfoUfDxZjdVKGSRWcommVRRuhXKuAwJJsRdQQtKCihsDdTGBljTdcCawHAzUwISISzMurGdZkhponWOgnmdctqQEGAoKXjrXhFUHupwnUegkDtdnPHXkqlePadRJSJfOIEfWJflcViNbRuGdQAiOUlXpAltXAWklflitqvcKfcfhiiEhbPqSEWAALYxlnqdHkTriLMDkzyaoebtZMcqzuryUeoAvEoNgJfTbpzMiXCmoolIiONjfXJBWWbaclPLDtQCAGeMROGhNqaiUOnIdNwOGkCCHoLQeAjidKylNEyXwYDgAeiaHFwroQIraOjqKIEBdujQFbOGjkijFyHbqnegxWZWwULEPFkmJXpDXhQUKPBzSKiyNJUSljqSJrJvEvefRdCzFIsxGhIllBRkjpVPjXDypmLHpAEDEwdPKhIfOlYTNgKFoHSufGEVDKOgsFVSbSnxUpRVUGWwPEPWtMBFXqlpmdHktmeKVBcQKLeUCYhnahySaaTlBeZXTqtoilYmlBlPkUXnDgzGlzJlPkOciJLJbzenpsPQMkOvdJiykRWuCTvDEGwsDAuddGMzdGYzTHCBKrkCuzuWFFcFmgZUdXJoYOJqjDvMAVlBVMprmDkyOnbpLTvjllYMSifGCoBYZRhBZJTGqMtyPhAFjcylYKXsHSicEstTFOeEsruynSJDupwgpjCcFFYMXFEMpSzAFguFUeJGTzQJQHjepBbkfBmwIJcnHVmrzTNFHVuPdybAYlHmbYCzrqSZIeiRYaqBputFfoCgvaZSBadGJuwPhDJiIBSQxAOwbpSYniuGDtJmQapoRnRnpuSGNwNIqfqQaxKTyHZxzRDHPaMnoQVYJFUvmTzHIyltAXrfggClhPhsGBjeEghyUPbltjJYEXgdjxfxMoBBcNCgoPXoLiUkvUhgdahTFNNfoRTJPjacnDLGYkGTrjPkwwyBgTsCEFTtYXeOCwGkiDlzlGvLAYGpEgOYIvVCfrcrHrUclNIVMpForGnsutFpyTETpipUPsZCIxkLOFUSimkjMJlXnhHrcSVmcvcJImDYURxxpFrctlRlLfTZrmTllmhqyeAcEEtVenZuuSOkXRlSsActARqCZpKkwjibfHBKLYrVHgYaRhRdDQFDTMIsAxcSiveerAdrDjFgqffNptMKXuvwwpqxIHkEBHmilpFpZPKTZaHGpspQnLuBIskQLfYNqIBZrAEgsexINyBxqnCsCAKZodCZdelbsWAYvFkjEaZpIvSlkkOvPCRgJdkTiBFnHSmFiwlmiWzztxEZAScKqdnOxmixyACsyNWYeWwskroGXQdwrYQDZAxazYUcJCpJCdGmXQwOyITYUBlsJxOtTqUVFtdfjKETCzCBPXHbchVMqTaCKAGJhqDOqmjgEgjoineiyALDQhsPaqTNKPBjhOJzwTvWRykgfVZdTvdoBQDqizoLanPzmrxRumtQrcsbuSuffXjnoAldvqKmZkmJmzmuGdyVqDRwBuVaHnOtaslDJWaaNTjqZheMnVparNyoouDijNMGYglJdDvmRbeTXcwKfeMLgtiurZPmGFbhqahNBhUsMraKdfBUmrEvubSprhiVmxYqwdoaowtdwuNSQreuPzmDejcBUnFPLnooEYeGlbSMwiGJEiCSicSXhHIDQxguPQouFKcmxREQDSvfKZqfOXkCRLSzaYVbuQKCZrYtgSGxtYNQHJbDTmtnkxDlIbhIDgDzfaTWUcFjzfwRoEhNiWWBxEKoyUInLjxMxcDDkpptcnMazcqNvNIJJaLWtcbaPZtqWKgbNLwZVlfIayfzrJxMBlyONZryRtGdDcAYnnEnvEFhtrxDTpEygvsZInHqvPgLRSpDRJTXFUTqNWYohoWjyAweBObwJIVlTNhHzQStJoSFTWVbSgaqRqSqmTBINytcRSrHlnvzdXdIadctmgUwIYNrVpYvnXKFHXBYwxXkxneIvyAWPowilsoeJbrUpkzoEBeHEhOwUvDniFeDjvnOVPJvCzsULGgqDwjRaKEHVghgpdjYPHiOFztAnDBQDYUeTobYdeeAXVUwgJHtytaXRdLlrSHTdchlWaQhmwBkZhntNOYqhuuMpfEhrBiKjrdUbobmmmvFlleZgKBvbOcfolfELLfRfZmPEbczJeDZdciuamVAgWqSxXUCxgEOjHkaQiCWiIcWLeGJhLcYaWIcggqlExgfAEogaFGAFPlUQCgKvPTGGAQoDudhnUWEGKCNyAaMbuwxiNtnlYMnLQVVMwQkUVVGYgPKPIYaVsUxaiNKTnVwUZUMOnEpLxRQsEHxTeQmrqifADgYcHLVzpapfoJorcFykYhhvIyIzBcxFvZZRejycuaMuJbyKgciWbLisRwVmAUtronLbNcAwDxwhvKLnxhRnNoKXSnTpDYesHYUGbszUiTxVAxzGkalefAckZuxhkbbeySSfxqrviRPMOonvhCcfIXbodNowuBwDkrzQPWvRCSxDbzcvLkgApksMFZAdMgGGSCDqDsBlMRXYFLgFeTgARrYKWKdBIAudDXbovzlXjpFMEORcpwbcTddBTTSVpOjoECfdAUMQiGANbFOaviGngwkEkcqKwBlxrAxYkcTpHEgZXJPeeQDBDDpLkXsmOuKwrmaHrDyZUxWjRfBiiGzeyjAjqpnNXQIkLIKbSzuIdusICKcoxqEpddmZLhlENyCstRDvItrUDOSmlbkOvmiYSSNFkNBPUVzeqwRQtDUIZpTOMmqOjVmJMZNlIiizdGLnmsVzwWWZFhzSvqBdazPucCropRgVvyMxYaxqvzeaPzlsvXcCESSjzISRRiXvxAVBlvXnvKMnjXqGtCYjWCYlbGFKxwcIgKKDgUMpfHnPYnoQQnDnOIshTOJCETzzwbFXqjWyqvgWZVqOfssYnkCvQfQWCSFFpeJccQBgIqrvjhUxWEczXPpTFEPSBNHZqDrjbtLAMyUeWRaVfIpLRMZojyWkbEroqbLAzlAJPNdurjlHYGcRxeduxAfoWrqIkmftmGaWNPoOeGasPrQszftFOoApNBlUQTZbeReRQLeAvkdkcxNQNlKECpbumiORUnsEptIfjbDmkoLpOWrDfetFUtoYdCOaCOGoMgxPHbmwAeGDbVMVhLivKkLBVATYxnDLkhpKYnibkoevJPILzmIzvqSbyqkTyZjANsRsMbIEvqRczsmdzJPGbSHYjWsOqFnmWDIvtoKrnkvXlDiukurlDiZHCxOkqjJAhFYNYIeCbCMhcPsdLfzrMkAVaAdmXKweVOyJQbqBQbvypPHkdquwJdnaYzrXTAavDSVOCdoJUljzsBwzDSMldBAUpvELpHQMPOBYIIDJrDJaXjesSaIzDTdiIohgOLwzkCFDDEVMqGteaUjsMCMYhMwWRCaPkJbpRJxtcQNlpUWCCUfokjPfYpohWWUCWqWEgwpZwIJnwuRwHozWUAiikLPfCFqctmJfiRgfiDMVHiFEvzyEOKaeKtmmRtoKH"));
	}

    public long longestSubstring(String s) {
		if (s.length() == 0) {
            return 0;
        }
        long max = 1;
		Map<Character, Integer> map = new HashMap<>();
		map.put(s.charAt(0), 0);
        long start = 0;
		for (int i = 1; i < s.length(); i++) {
			Integer p = map.get(s.charAt(i));
			if (p != null && p >= start) {
                start = p + 1;
			}
			map.put(s.charAt(i), i);
			max = Math.max(max, i - start + 1);
		}

		return max;
	}

}
