package string;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

// leet code Problem #30
public class SubstringConcat {

    public static void main(String[] args) {
        SubstringConcat obj = new SubstringConcat();
        System.out.println(obj.findSubstring("barfoothefoobarman",
                new String[] { "foo", "bar" }));
        System.out.println(obj.findSubstring("wordgoodgoodgoodbestword",
                new String[] { "word", "good", "best", "word" }));
        System.out.println(obj.findSubstring(
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                new String[] { "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                        "a", "a", "a", "a", "a", "a", "a", "a" }));
    }

    int wordLength = 0;
    public List<Integer> findSubstring(String s, String[] words) {
        TreeMap<Integer, List<Integer>> map = new TreeMap<>();
        wordLength = words.length > 0 ? words[0].length() : 0;
        List<Integer> ans = new ArrayList<>();
        if (s.length() < wordLength * words.length) {
            return ans;
        }
        for (int i = 0; i < words.length; i++) {
            addIndeces(s, words[i], i, map);
        }
        // System.out.println(map.toString());

        for (Integer j : map.keySet()) {
            if (s.length() - j < wordLength * words.length) {
                break;
            }
            if (isSub(map, j, new boolean[words.length], 0)) {
                ans.add(j);
            }
        }
        return ans;
    }

    private boolean isSub(TreeMap<Integer, List<Integer>> map, Integer j,
            boolean[] b, int k) {
        List<Integer> l = map.get(j);
        if (l == null) {
            return false;
        }
        for(Integer i:l) {
            if(!b[i]) {
                b[i]=true;
                k++;
                return k == b.length || isSub(map, j + wordLength, b, k);
            }
        }

        return false;
    }

    private void addIndeces(String s, String sub, int i,
            TreeMap<Integer, List<Integer>> map) {
        for (int j = 0; j + sub.length() <= s.length(); j++) {
            if (s.substring(j, j + sub.length()).equals(sub)) {
                List<Integer> l = map.get(j);
                if (l == null) {
                    l = new ArrayList<Integer>();
                    map.put(j, l);
                }
                l.add(i);
            }
        }

    }

}
